import * as Knex from '../../migrations/knex';

const tableName = 'room';

exports.seed = async (knex: Knex) => {
  // Deletes ALL existing entries
  await knex(tableName).del();
  // Inserts seed entries
  return knex(tableName).insert([
    // Chapter 9
    // Ch9 Start
    { id: 1, room_number: 1, debug_id: 'intro-00-past', checkpoint_id: 1 },
    { id: 2, room_number: 2, debug_id: 'intro-01-future', checkpoint_id: 1 },
    { id: 3, room_number: 3, debug_id: 'intro-02-launch', checkpoint_id: 1 },
    { id: 4, room_number: 4, debug_id: 'intro-03-space', checkpoint_id: 1 },
    // Ch9 Singular
    { id: 5, room_number: 1, debug_id: 'a-00', checkpoint_id: 2 },
    { id: 6, room_number: 2, debug_id: 'a-01', checkpoint_id: 2 },
    { id: 7, room_number: 3, debug_id: 'a-02', checkpoint_id: 2 },
    { id: 8, room_number: 4, debug_id: 'a-03', checkpoint_id: 2 },
    { id: 9, room_number: 5, debug_id: 'a-04', checkpoint_id: 2 },
    { id: 10, room_number: 6, debug_id: 'a-05', checkpoint_id: 2 },
    { id: 11, room_number: 7, debug_id: 'b-00', checkpoint_id: 2 },
    { id: 12, room_number: 8, debug_id: 'b-01', checkpoint_id: 2 },
    { id: 13, room_number: 9, debug_id: 'b-02', checkpoint_id: 2 },
    { id: 14, room_number: 10, debug_id: 'b-03', checkpoint_id: 2 },
    { id: 15, room_number: 11, debug_id: 'b-04', checkpoint_id: 2 },
    { id: 16, room_number: 12, debug_id: 'b-05', checkpoint_id: 2 },
    { id: 17, room_number: 13, debug_id: 'b-06', checkpoint_id: 2 },
    { id: 18, room_number: 14, debug_id: 'b-07', checkpoint_id: 2 },
    // Ch9 Power Source
    { id: 19, room_number: 1, debug_id: 'c-00', checkpoint_id: 3 },
    { id: 20, room_number: 2, debug_id: 'c-00-b', checkpoint_id: 3 },
    { id: 21, room_number: 3, debug_id: 'c-alt-00', checkpoint_id: 3 },
    { id: 22, room_number: 4, debug_id: 'c-alt-01', checkpoint_id: 3 },
    { id: 23, room_number: 5, debug_id: 'c-01', checkpoint_id: 3 },
    { id: 24, room_number: 6, debug_id: 'c-02', checkpoint_id: 3 },
    { id: 25, room_number: 7, debug_id: 'c-03', checkpoint_id: 3 },
    { id: 26, room_number: 8, debug_id: 'd-00', checkpoint_id: 3 },
    { id: 27, room_number: 9, debug_id: 'd-01', checkpoint_id: 3 },
    { id: 28, room_number: 10, debug_id: 'd-02', checkpoint_id: 3 },
    { id: 29, room_number: 11, debug_id: 'd-03', checkpoint_id: 3 },
    { id: 30, room_number: 12, debug_id: 'd-04', checkpoint_id: 3 },
    { id: 31, room_number: 13, debug_id: 'd-05', checkpoint_id: 3 },
    { id: 32, room_number: 14, debug_id: 'e-00y', checkpoint_id: 3 },
    { id: 33, room_number: 15, debug_id: 'e-00yb', checkpoint_id: 3 },
    // Ch9 Remembered
    { id: 34, room_number: 1, debug_id: 'e-00z', checkpoint_id: 4 },
    { id: 35, room_number: 2, debug_id: 'e-00', checkpoint_id: 4 },
    { id: 36, room_number: 3, debug_id: 'e-00b', checkpoint_id: 4 },
    { id: 37, room_number: 4, debug_id: 'e-01', checkpoint_id: 4 },
    { id: 38, room_number: 5, debug_id: 'e-02', checkpoint_id: 4 },
    { id: 39, room_number: 6, debug_id: 'e-03', checkpoint_id: 4 },
    { id: 40, room_number: 7, debug_id: 'e-04', checkpoint_id: 4 },
    { id: 41, room_number: 8, debug_id: 'e-05', checkpoint_id: 4 },
    { id: 42, room_number: 9, debug_id: 'e-05b', checkpoint_id: 4 },
    { id: 43, room_number: 10, debug_id: 'e-05c', checkpoint_id: 4 },
    { id: 44, room_number: 11, debug_id: 'e-06', checkpoint_id: 4 },
    { id: 45, room_number: 12, debug_id: 'e-07', checkpoint_id: 4 },
    { id: 46, room_number: 13, debug_id: 'e-08', checkpoint_id: 4 },
    // Ch9 Event Horizon
    { id: 47, room_number: 1, debug_id: 'f-door', checkpoint_id: 5 },
    { id: 48, room_number: 2, debug_id: 'f-00', checkpoint_id: 5 },
    { id: 49, room_number: 3, debug_id: 'f-01', checkpoint_id: 5 },
    { id: 50, room_number: 4, debug_id: 'f-02', checkpoint_id: 5 },
    { id: 51, room_number: 5, debug_id: 'f-03', checkpoint_id: 5 },
    { id: 52, room_number: 6, debug_id: 'f-04', checkpoint_id: 5 },
    { id: 53, room_number: 7, debug_id: 'f-05', checkpoint_id: 5 },
    { id: 54, room_number: 8, debug_id: 'f-06', checkpoint_id: 5 },
    { id: 55, room_number: 9, debug_id: 'f-07', checkpoint_id: 5 },
    { id: 56, room_number: 10, debug_id: 'f-08', checkpoint_id: 5 },
    { id: 57, room_number: 11, debug_id: 'f-09', checkpoint_id: 5 },
    { id: 58, room_number: 12, debug_id: 'g-00', checkpoint_id: 5 },
    { id: 59, room_number: 13, debug_id: 'g-01', checkpoint_id: 5 },
    { id: 60, room_number: 14, debug_id: 'g-03', checkpoint_id: 5 },
    { id: 61, room_number: 15, debug_id: 'g-02', checkpoint_id: 5 },
    { id: 62, room_number: 16, debug_id: 'g-04', checkpoint_id: 5 },
    { id: 63, room_number: 17, debug_id: 'g-05', checkpoint_id: 5 },
    { id: 64, room_number: 18, debug_id: 'g-06', checkpoint_id: 5 },
    // Ch9 Determination
    { id: 65, room_number: 1, debug_id: 'h-00b', checkpoint_id: 6 },
    { id: 66, room_number: 2, debug_id: 'h-00', checkpoint_id: 6 },
    { id: 67, room_number: 3, debug_id: 'h-01', checkpoint_id: 6 },
    { id: 68, room_number: 4, debug_id: 'h-02', checkpoint_id: 6 },
    { id: 69, room_number: 5, debug_id: 'h-03', checkpoint_id: 6 },
    { id: 70, room_number: 6, debug_id: 'h-03b', checkpoint_id: 6 },
    { id: 71, room_number: 7, debug_id: 'h-04', checkpoint_id: 6 },
    { id: 72, room_number: 8, debug_id: 'h-04b', checkpoint_id: 6 },
    { id: 73, room_number: 9, debug_id: 'h-05', checkpoint_id: 6 },
    { id: 74, room_number: 10, debug_id: 'h-06', checkpoint_id: 6 },
    { id: 75, room_number: 11, debug_id: 'h-06b', checkpoint_id: 6 },
    { id: 76, room_number: 12, debug_id: 'h-07', checkpoint_id: 6 },
    { id: 77, room_number: 13, debug_id: 'h-08', checkpoint_id: 6 },
    { id: 78, room_number: 14, debug_id: 'h-09', checkpoint_id: 6 },
    { id: 79, room_number: 15, debug_id: 'h-10', checkpoint_id: 6 },
    // Ch9 Stubbornness
    { id: 80, room_number: 1, debug_id: 'i-00', checkpoint_id: 7 },
    { id: 81, room_number: 2, debug_id: 'i-00b', checkpoint_id: 7 },
    { id: 82, room_number: 3, debug_id: 'i-01', checkpoint_id: 7 },
    { id: 83, room_number: 4, debug_id: 'i-02', checkpoint_id: 7 },
    { id: 84, room_number: 5, debug_id: 'i-03', checkpoint_id: 7 },
    { id: 85, room_number: 6, debug_id: 'i-04', checkpoint_id: 7 },
    { id: 86, room_number: 7, debug_id: 'i-05', checkpoint_id: 7 },
    // Ch9 Reconciliation
    { id: 87, room_number: 1, debug_id: 'j-00', checkpoint_id: 8 },
    { id: 88, room_number: 2, debug_id: 'j-00b', checkpoint_id: 8 },
    { id: 89, room_number: 3, debug_id: 'j-01', checkpoint_id: 8 },
    { id: 90, room_number: 4, debug_id: 'j-02', checkpoint_id: 8 },
    { id: 91, room_number: 5, debug_id: 'j-03', checkpoint_id: 8 },
    { id: 92, room_number: 6, debug_id: 'j-04', checkpoint_id: 8 },
    { id: 93, room_number: 7, debug_id: 'j-05', checkpoint_id: 8 },
    { id: 94, room_number: 8, debug_id: 'j-06', checkpoint_id: 8 },
    { id: 95, room_number: 9, debug_id: 'j-07', checkpoint_id: 8 },
    { id: 96, room_number: 10, debug_id: 'j-08', checkpoint_id: 8 },
    { id: 97, room_number: 11, debug_id: 'j-09', checkpoint_id: 8 },
    { id: 98, room_number: 12, debug_id: 'j-10', checkpoint_id: 8 },
    { id: 99, room_number: 13, debug_id: 'j-11', checkpoint_id: 8 },
    { id: 100, room_number: 14, debug_id: 'j-12', checkpoint_id: 8 },
    { id: 101, room_number: 15, debug_id: 'j-13', checkpoint_id: 8 },
    { id: 102, room_number: 16, debug_id: 'j-14', checkpoint_id: 8 },
    { id: 103, room_number: 17, debug_id: 'j-14b', checkpoint_id: 8 },
    { id: 104, room_number: 18, debug_id: 'j-15', checkpoint_id: 8 },
    // Ch9 Farewell
    { id: 105, room_number: 1, debug_id: 'j-16', checkpoint_id: 9 },
    { id: 106, room_number: 2, debug_id: 'j-17', checkpoint_id: 9 },
    { id: 107, room_number: 3, debug_id: 'j-18', checkpoint_id: 9 },
    { id: 108, room_number: 4, debug_id: 'j-19', checkpoint_id: 9 },
    { id: 109, room_number: 5, debug_id: 'end-golden', checkpoint_id: 9 },
  ]);
}